spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_springdata
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
server:
  port: 8088


