logging:
  level: debug
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_springdata
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
  data:
    elasticsearch:
      cluster-name:
      cluster-nodes: 172.16.199.126:9200
#  redis:
#    host: 172.16.199.126
#    port: 6379
#    password:
#    database: 5
#    pool:
#      max-active: 8
#      max-wait: -1
#      max-idle: 8
#      min-idle: 0
#    timeout: 1000
server:
  port: 8088



